from typing import Optional

TagId = int
ObjectId = int

def init() -> None: ...

class SurfaceInfo:
    def __init__(
        self,
        logical_width: int,
        logical_height: int,
        physical_width: int,
        physical_height: int,
        content_scale_x: float,
        content_scale_y: float,
    ): ...

class Engine:
    def __init__(self, reader: AbstractReader): ...
    def render(self, playback_value: float) -> None: ...
    def resize(self, surface_info: SurfaceInfo) -> None: ...
    def setRandomGlobalDiffuse(self) -> None: ...
    def currentCameraStateMut(self) -> CameraState: ...
    def runtimeModelMut(self) -> RuntimeModel: ...
    def prepareToRender(self, surface_info: SurfaceInfo) -> None: ...

class RuntimeModel:
    def rootObjectId(self) -> ObjectId: ...
    def getObjectName(self, id: ObjectId) -> str: ...
    def getObjectChildrenCount(self, id: ObjectId) -> int: ...
    def getObjectChild(self, id: ObjectId, index: int) -> ObjectId: ...
    def getTagCount(self) -> TagId: ...
    def getTag(self, index: int) -> TagId: ...
    def getTagName(self, id: TagId) -> str: ...
    def getTagVisibility(self, id: TagId) -> bool: ...
    def setTagVisibility(self, id: TagId, visibility: bool) -> None: ...
    def selectedObjectIdOpt(self) -> Optional[ObjectId]: ...
    def updateObjectSelectionById(self, object_id: Optional[ObjectId]): ...

class AbstractReader: ...

class AssimpReader(AbstractReader):
    def __init__(self, resource_path: str, /): ...

class SketchupReader(AbstractReader):
    def __init__(self, resource_path: str, /): ...

class Vec3:
    def __init__(self) -> None: ...
    def __mul__(self, other: float) -> Vec3: ...
    def __rmul__(self, other: float) -> Vec3: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    x: float
    y: float
    z: float

class CameraState:
    def __init__(self) -> None: ...
    def front(self) -> Vec3: ...
    def left(self) -> Vec3: ...
    fovyDef: float
    aspectWidth: float
    aspectHeight: float
    zNear: float
    zFar: float
    pos: Vec3
    up: Vec3
    speed: float
    pitch: float
    yaw: float
